#!/bin/sh

# See https://wiki.archlinux.org/index.php/Kernels/Traditional_compilation

set -x
make -j8 || exit 1
sudo make modules_install
sudo cp -v arch/x86/boot/bzImage /boot/vmlinuz-pspat
sudo mkinitcpio -k $(make kernelrelease) -g /boot/initramfs-pspat.img
